---
# handlers file for elastic-config
- name: restart ES on master
  ansible.builtin.service:
    name: elasticsearch
    state: restarted
  when: inventory_hostname in groups['es-cluster-master']

- name: restart ES on secondary
  ansible.builtin.service:
    name: elasticsearch
    state: restarted
  when: inventory_hostname in groups['es-cluster-replicas']