---
# tasks file for kibana-with-user
- name: Modify kibana.yml to authentificate without user
  ansible.builtin.template:
    src: templates/kibana.yml.j2
    dest: /etc/kibana/kibana.yml
  when: inventory_hostname in groups['es-cluster-master']
  notify: 
     - restart kibana on master
  